/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea.lang;

import org.sqlproc.meta.idea.lang.AbstractProcessorMetaFileType;

@SuppressWarnings("all")
public class ProcessorMetaFileType extends AbstractProcessorMetaFileType {
  public final static ProcessorMetaFileType INSTANCE = new ProcessorMetaFileType();
  
  public ProcessorMetaFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(ProcessorMetaLanguage) is undefined");
  }
}
