/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.processorModel.impl;

import org.eclipse.emf.ecore.EClass;

import org.sqlproc.model.processorModel.AnnotationDirectiveAttribute;
import org.sqlproc.model.processorModel.ProcessorModelPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Annotation Directive Attribute</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class AnnotationDirectiveAttributeImpl extends AnnotationDirectiveImpl implements AnnotationDirectiveAttribute
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AnnotationDirectiveAttributeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return ProcessorModelPackage.Literals.ANNOTATION_DIRECTIVE_ATTRIBUTE;
  }

} //AnnotationDirectiveAttributeImpl
