/*
 * generated by Xtext 2.12.0
 */
package org.sqlproc.meta.idea.completion;

import org.eclipse.xtext.idea.completion.AbstractCompletionContributor;
import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public class AbstractProcessorMetaCompletionContributor extends AbstractCompletionContributor {
	public AbstractProcessorMetaCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
