/**
 * generated by Xtext
 */
package org.sqlproc.model.validation;

import com.google.common.base.Objects;
import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.xtext.EcoreUtil2;
import org.eclipse.xtext.validation.Check;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.sqlproc.model.processorModel.AbstractEntity;
import org.sqlproc.model.processorModel.AnnotatedEntity;
import org.sqlproc.model.processorModel.AnnotatedFeature;
import org.sqlproc.model.processorModel.AnnotationDefinitionModel;
import org.sqlproc.model.processorModel.Artifacts;
import org.sqlproc.model.processorModel.DaoEntity;
import org.sqlproc.model.processorModel.Entity;
import org.sqlproc.model.processorModel.Feature;
import org.sqlproc.model.processorModel.FunctionDefinitionModel;
import org.sqlproc.model.processorModel.PojoDefinitionModel;
import org.sqlproc.model.processorModel.PojoEntity;
import org.sqlproc.model.processorModel.ProcedureDefinitionModel;
import org.sqlproc.model.processorModel.ProcessorModelPackage;
import org.sqlproc.model.processorModel.Property;
import org.sqlproc.model.processorModel.TableDefinitionModel;
import org.sqlproc.model.validation.AbstractProcessorModelValidator;
import org.sqlproc.plugin.lib.property.ModelProperty;
import org.sqlproc.plugin.lib.resolver.DbResolver;
import org.sqlproc.plugin.lib.util.CommonUtils;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class ProcessorModelValidator extends AbstractProcessorModelValidator {
  @Inject
  private DbResolver dbResolver;
  
  @Inject
  private ModelProperty modelProperty;
  
  @Check
  public void checkUniquePojoDefinition(final PojoDefinitionModel pojoDefinition) {
    boolean _skipVerification = CommonUtils.skipVerification(pojoDefinition, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Artifacts artifacts = this.getArtifacts(pojoDefinition);
    boolean _equals = Objects.equal(artifacts, null);
    if (_equals) {
      return;
    }
    EList<PojoDefinitionModel> _pojos = artifacts.getPojos();
    for (final PojoDefinitionModel definition : _pojos) {
      if ((((!Objects.equal(definition, null)) && (definition != pojoDefinition)) && Objects.equal(pojoDefinition.getName(), definition.getName()))) {
        String _name = pojoDefinition.getName();
        String _plus = ("Duplicate name : " + _name);
        this.error(_plus, ProcessorModelPackage.Literals.POJO_DEFINITION_MODEL__NAME);
        return;
      }
    }
  }
  
  @Check
  public void checkUniqueAnnotationDefinition(final AnnotationDefinitionModel annotationDefinition) {
    boolean _skipVerification = CommonUtils.skipVerification(annotationDefinition, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Artifacts artifacts = this.getArtifacts(annotationDefinition);
    boolean _equals = Objects.equal(artifacts, null);
    if (_equals) {
      return;
    }
    EList<AnnotationDefinitionModel> _annotations = artifacts.getAnnotations();
    for (final AnnotationDefinitionModel definition : _annotations) {
      if ((((!Objects.equal(definition, null)) && (definition != annotationDefinition)) && Objects.equal(annotationDefinition.getName(), definition.getName()))) {
        String _name = annotationDefinition.getName();
        String _plus = ("Duplicate name : " + _name);
        this.error(_plus, ProcessorModelPackage.Literals.ANNOTATION_DEFINITION_MODEL__NAME);
        return;
      }
    }
  }
  
  @Check
  public void checkUniqueProperty(final Property property) {
    boolean _skipVerification = CommonUtils.skipVerification(property, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Artifacts artifacts = this.getArtifacts(property);
    boolean _equals = Objects.equal(artifacts, null);
    if (_equals) {
      return;
    }
    EList<Property> _properties = artifacts.getProperties();
    for (final Property prop : _properties) {
      if ((((!Objects.equal(prop, null)) && (prop != property)) && Objects.equal(prop.getName(), property.getName()))) {
        if ((((((!prop.getName().startsWith("pojogen")) && (!prop.getName().startsWith("database"))) && (!prop.getName().startsWith("metagen"))) && (!prop.getName().startsWith("daogen"))) && (!prop.getName().startsWith("replace-text")))) {
          String _name = property.getName();
          String _plus = ("Duplicate name : " + _name);
          this.error(_plus, ProcessorModelPackage.Literals.PROPERTY__NAME);
          return;
        }
      }
    }
  }
  
  @Check
  public void checkTableDefinition(final TableDefinitionModel tableDefinition) {
    boolean _skipVerification = CommonUtils.skipVerification(tableDefinition, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Artifacts artifacts = this.getArtifacts(tableDefinition);
    boolean _equals = Objects.equal(artifacts, null);
    if (_equals) {
      return;
    }
    EList<TableDefinitionModel> _tables = artifacts.getTables();
    for (final TableDefinitionModel table : _tables) {
      if ((((!Objects.equal(table, null)) && (table != tableDefinition)) && Objects.equal(tableDefinition.getName(), table.getName()))) {
        String _name = tableDefinition.getName();
        String _plus = ("Duplicate name : " + _name);
        String _plus_1 = (_plus + "[table]");
        this.error(_plus_1, ProcessorModelPackage.Literals.TABLE_DEFINITION_MODEL__NAME);
        return;
      }
    }
    if ((this.isResolveDb(tableDefinition) && (!this.dbResolver.checkTable(tableDefinition, tableDefinition.getTable())))) {
      String _table = tableDefinition.getTable();
      String _plus_2 = ("Cannot find table in DB : " + _table);
      this.error(_plus_2, ProcessorModelPackage.Literals.TABLE_DEFINITION_MODEL__TABLE);
    }
  }
  
  @Check
  public void checkProcedureDefinition(final ProcedureDefinitionModel procedureDefinition) {
    boolean _skipVerification = CommonUtils.skipVerification(procedureDefinition, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Artifacts artifacts = this.getArtifacts(procedureDefinition);
    boolean _equals = Objects.equal(artifacts, null);
    if (_equals) {
      return;
    }
    EList<ProcedureDefinitionModel> _procedures = artifacts.getProcedures();
    for (final ProcedureDefinitionModel procedure : _procedures) {
      if ((((!Objects.equal(procedure, null)) && (procedure != procedureDefinition)) && Objects.equal(procedureDefinition.getName(), procedure.getName()))) {
        String _name = procedureDefinition.getName();
        String _plus = ("Duplicate name : " + _name);
        String _plus_1 = (_plus + "[procedure]");
        this.error(_plus_1, ProcessorModelPackage.Literals.PROCEDURE_DEFINITION_MODEL__NAME);
        return;
      }
    }
    if ((this.isResolveDb(procedureDefinition) && (!this.dbResolver.checkProcedure(procedureDefinition, procedureDefinition.getTable())))) {
      String _table = procedureDefinition.getTable();
      String _plus_2 = ("Cannot find procedure in DB : " + _table);
      this.error(_plus_2, ProcessorModelPackage.Literals.PROCEDURE_DEFINITION_MODEL__NAME);
    }
  }
  
  @Check
  public void checkFunctionDefinition(final FunctionDefinitionModel functionDefinition) {
    boolean _skipVerification = CommonUtils.skipVerification(functionDefinition, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Artifacts artifacts = this.getArtifacts(functionDefinition);
    boolean _equals = Objects.equal(artifacts, null);
    if (_equals) {
      return;
    }
    EList<FunctionDefinitionModel> _functions = artifacts.getFunctions();
    for (final FunctionDefinitionModel function : _functions) {
      if ((((!Objects.equal(function, null)) && (function != functionDefinition)) && Objects.equal(functionDefinition.getName(), function.getName()))) {
        String _name = functionDefinition.getName();
        String _plus = ("Duplicate name : " + _name);
        String _plus_1 = (_plus + "[function]");
        this.error(_plus_1, ProcessorModelPackage.Literals.FUNCTION_DEFINITION_MODEL__NAME);
        return;
      }
    }
  }
  
  @Check
  public void checkUniquePojoEntity(final Entity entity) {
    boolean _skipVerification = CommonUtils.skipVerification(entity, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Artifacts artifacts = this.getArtifacts(entity);
    boolean _equals = Objects.equal(artifacts, null);
    if (_equals) {
      return;
    }
    EList<org.sqlproc.model.processorModel.Package> _packages = artifacts.getPackages();
    for (final org.sqlproc.model.processorModel.Package pkg : _packages) {
      boolean _notEquals = (!Objects.equal(pkg, null));
      if (_notEquals) {
        EList<AbstractEntity> _elements = pkg.getElements();
        for (final AbstractEntity abstractEntity : _elements) {
          if (((!Objects.equal(abstractEntity, null)) && (abstractEntity instanceof AnnotatedEntity))) {
            final AnnotatedEntity annotatedEntity = ((AnnotatedEntity) abstractEntity);
            Entity _entity = annotatedEntity.getEntity();
            boolean _notEquals_1 = (!Objects.equal(_entity, null));
            if (_notEquals_1) {
              Entity _entity_1 = annotatedEntity.getEntity();
              final Entity _entity_2 = ((Entity) _entity_1);
              if ((((!Objects.equal(_entity_2, null)) && (_entity_2 != entity)) && Objects.equal(entity.getName(), _entity_2.getName()))) {
                String _name = entity.getName();
                String _plus = ("Duplicate name : " + _name);
                this.error(_plus, ProcessorModelPackage.Literals.ENTITY__NAME);
                return;
              }
            }
          }
        }
      }
    }
  }
  
  @Check
  public void checkUniquePojoAttribute(final Feature feature) {
    boolean _skipVerification = CommonUtils.skipVerification(feature, this.modelProperty);
    if (_skipVerification) {
      return;
    }
    final Entity entity = EcoreUtil2.<Entity>getContainerOfType(feature, Entity.class);
    boolean _notEquals = (!Objects.equal(entity, null));
    if (_notEquals) {
      if ((entity instanceof PojoEntity)) {
        final PojoEntity pentity = ((PojoEntity) entity);
        final Function1<AnnotatedFeature, Feature> _function = (AnnotatedFeature it) -> {
          return feature;
        };
        List<Feature> _map = ListExtensions.<AnnotatedFeature, Feature>map(pentity.getFeatures(), _function);
        for (final Feature _feature : _map) {
          if ((((!Objects.equal(_feature, null)) && (_feature != feature)) && Objects.equal(feature.getName(), _feature.getName()))) {
            String _name = feature.getName();
            String _plus = ("Duplicate name : " + _name);
            this.error(_plus, ProcessorModelPackage.Literals.FEATURE__NAME);
            return;
          }
        }
      } else {
        if ((entity instanceof DaoEntity)) {
          final DaoEntity pentity_1 = ((DaoEntity) entity);
          final Function1<AnnotatedFeature, Feature> _function_1 = (AnnotatedFeature it) -> {
            return feature;
          };
          List<Feature> _map_1 = ListExtensions.<AnnotatedFeature, Feature>map(pentity_1.getFeatures(), _function_1);
          for (final Feature _feature_1 : _map_1) {
            if ((((!Objects.equal(_feature_1, null)) && (_feature_1 != feature)) && Objects.equal(feature.getName(), _feature_1.getName()))) {
              String _name_1 = feature.getName();
              String _plus_1 = ("Duplicate name : " + _name_1);
              this.error(_plus_1, ProcessorModelPackage.Literals.FEATURE__NAME);
              return;
            }
          }
        }
      }
    }
  }
  
  public boolean isResolveDb(final EObject model) {
    return this.dbResolver.isResolveDb(model);
  }
  
  public Artifacts getArtifacts(final EObject model) {
    final EObject root = EcoreUtil.getRootContainer(model);
    if ((!(root instanceof Artifacts))) {
      return null;
    }
    return ((Artifacts) root);
  }
}
