/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta;

import org.sqlproc.meta.ProcessorMetaStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ProcessorMetaStandaloneSetup extends ProcessorMetaStandaloneSetupGenerated {
  public static void doSetup() {
    ProcessorMetaStandaloneSetup _processorMetaStandaloneSetup = new ProcessorMetaStandaloneSetup();
    _processorMetaStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
