/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.sqlproc.model.idea.lang.ProcessorModelLanguage

class ProcessorModelCompletionContributor extends AbstractProcessorModelCompletionContributor {
	new() {
		this(ProcessorModelLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
