/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea.highlighting;

import org.eclipse.xtext.idea.highlighting.AbstractColorSettingsPage;
import org.sqlproc.meta.idea.lang.ProcessorMetaLanguage;

public class ProcessorMetaBaseColorSettingsPage extends AbstractColorSettingsPage {
	
	public ProcessorMetaBaseColorSettingsPage() {
		ProcessorMetaLanguage.INSTANCE.injectMembers(this);
	}

	@Override
	public String getDisplayName() {
		return ProcessorMetaLanguage.INSTANCE.getDisplayName();
	}
}
