/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea;

@SuppressWarnings("all")
public class ProcessorModelIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nensureInitialized cannot be resolved");
  }
}
