/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea;

import org.sqlproc.model.idea.AbstractProcessorModelIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class ProcessorModelIdeaModule extends AbstractProcessorModelIdeaModule {
}
