/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea.highlighting;

import org.sqlproc.meta.idea.highlighting.ProcessorMetaBaseColorSettingsPage;

@SuppressWarnings("all")
public class ProcessorMetaColorSettingsPage extends ProcessorMetaBaseColorSettingsPage {
}
