CREATE TABLE UUID_ENTITY (
  ID UUID DEFAULT gen_random_uuid() NOT NULL,
  MYID UUID DEFAULT gen_random_uuid() NOT NULL,
  NAME VARCHAR(100) NOT NULL,
  DESCRIPTION VARCHAR(500)
);

ALTER TABLE UUID_ENTITY ADD CONSTRAINT PK_UUID_ENTITY
	PRIMARY KEY (ID);
