/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class ProcessorMetaFacetConfiguration /* implements AbstractFacetConfiguration, PersistentStateComponent<GeneratorConfigurationState>  */{
}
