/*
 * generated by Xtext 2.12.0
 */
package org.sqlproc.model.scoping;

import org.eclipse.xtext.xbase.annotations.typesystem.XbaseWithAnnotationsBatchScopeProvider;

public abstract class AbstractProcessorModelScopeProvider extends XbaseWithAnnotationsBatchScopeProvider {
}
