/*
 * generated by Xtext 2.12.0
 */
package org.sqlproc.meta.idea.lang;

import com.intellij.lang.Language;
import com.intellij.openapi.fileTypes.LanguageFileType;
import javax.swing.Icon;
import org.eclipse.xtext.idea.Icons;
import org.jetbrains.annotations.NonNls;

public class AbstractProcessorMetaFileType extends LanguageFileType {

	@NonNls 
	public static final String DEFAULT_EXTENSION = "meta";

	protected AbstractProcessorMetaFileType(final Language language) {
		super(language);
	}

	@Override
	public String getDefaultExtension() {
		return DEFAULT_EXTENSION;
	}

	@Override
	public String getDescription() {
		return "ProcessorMeta files";
	}

	@Override
	public Icon getIcon() {
		return Icons.DSL_FILE_TYPE;
	}

	@Override
	public String getName() {
		return "ProcessorMeta";
	}

}
