/*
 * generated by Xtext 2.10.0
 */
package org.sqlproc.model.idea.lang;

import com.intellij.openapi.fileTypes.FileTypeConsumer;
import com.intellij.openapi.fileTypes.FileTypeFactory;
import org.jetbrains.annotations.NotNull;

public class ProcessorModelFileTypeFactory extends FileTypeFactory {

	@Override
	public void createFileTypes(@NotNull FileTypeConsumer consumer) {
		consumer.consume(ProcessorModelFileType.INSTANCE, AbstractProcessorModelFileType.DEFAULT_EXTENSION);
	}

}
