/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class ProcessorModelLanguage extends AbstractXtextLanguage {

	public static final ProcessorModelLanguage INSTANCE = new ProcessorModelLanguage();

	private ProcessorModelLanguage() {
		super("org.sqlproc.model.ProcessorModel");
	}

}
