/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.web

import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor

/**
 * Use this class to register additional components to be used within the web application.
 */
@FinalFieldsConstructor
class ProcessorModelWebModule extends AbstractProcessorModelWebModule {
}
