/*
 * generated by Xtext 2.10.0
 */
package org.sqlproc.model.idea.completion;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;
import org.eclipse.xtext.xbase.annotations.idea.completion.XbaseWithAnnotationsCompletionContributor;

public class AbstractProcessorModelCompletionContributor extends XbaseWithAnnotationsCompletionContributor {
	public AbstractProcessorModelCompletionContributor(AbstractXtextLanguage lang) {
		super(lang);
	}
}
