/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea.completion

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage
import org.sqlproc.meta.idea.lang.ProcessorMetaLanguage

class ProcessorMetaCompletionContributor extends AbstractProcessorMetaCompletionContributor {
	new() {
		this(ProcessorMetaLanguage.INSTANCE)
	}
	
	new(AbstractXtextLanguage lang) {
		super(lang)
		//custom rules here
	}
}
