/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.highlighting;

import org.sqlproc.model.idea.highlighting.ProcessorModelBaseColorSettingsPage;

@SuppressWarnings("all")
public class ProcessorModelColorSettingsPage extends ProcessorModelBaseColorSettingsPage {
}
