/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.lang;

import org.sqlproc.model.idea.lang.AbstractProcessorModelFileType;

@SuppressWarnings("all")
public class ProcessorModelFileType extends AbstractProcessorModelFileType {
  public final static ProcessorModelFileType INSTANCE = new ProcessorModelFileType();
  
  public ProcessorModelFileType() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(ProcessorModelLanguage) is undefined");
  }
}
