/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.processorModel;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function Call Query</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sqlproc.model.processorModel.ProcessorModelPackage#getFunctionCallQuery()
 * @model
 * @generated
 */
public interface FunctionCallQuery extends FunProcType
{
} // FunctionCallQuery
