/**
 * generated by Xtext 2.10.0
 */
package org.sqlproc.model.processorModel;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Sql Type Assignement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sqlproc.model.processorModel.SqlTypeAssignement#getSqlType <em>Sql Type</em>}</li>
 *   <li>{@link org.sqlproc.model.processorModel.SqlTypeAssignement#getSqlSize <em>Sql Size</em>}</li>
 *   <li>{@link org.sqlproc.model.processorModel.SqlTypeAssignement#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.sqlproc.model.processorModel.ProcessorModelPackage#getSqlTypeAssignement()
 * @model
 * @generated
 */
public interface SqlTypeAssignement extends EObject
{
  /**
   * Returns the value of the '<em><b>Sql Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sql Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sql Type</em>' containment reference.
   * @see #setSqlType(ValueType)
   * @see org.sqlproc.model.processorModel.ProcessorModelPackage#getSqlTypeAssignement_SqlType()
   * @model containment="true"
   * @generated
   */
  ValueType getSqlType();

  /**
   * Sets the value of the '{@link org.sqlproc.model.processorModel.SqlTypeAssignement#getSqlType <em>Sql Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sql Type</em>' containment reference.
   * @see #getSqlType()
   * @generated
   */
  void setSqlType(ValueType value);

  /**
   * Returns the value of the '<em><b>Sql Size</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Sql Size</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Sql Size</em>' attribute.
   * @see #setSqlSize(int)
   * @see org.sqlproc.model.processorModel.ProcessorModelPackage#getSqlTypeAssignement_SqlSize()
   * @model
   * @generated
   */
  int getSqlSize();

  /**
   * Sets the value of the '{@link org.sqlproc.model.processorModel.SqlTypeAssignement#getSqlSize <em>Sql Size</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Sql Size</em>' attribute.
   * @see #getSqlSize()
   * @generated
   */
  void setSqlSize(int value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' containment reference.
   * @see #setType(PojoType)
   * @see org.sqlproc.model.processorModel.ProcessorModelPackage#getSqlTypeAssignement_Type()
   * @model containment="true"
   * @generated
   */
  PojoType getType();

  /**
   * Sets the value of the '{@link org.sqlproc.model.processorModel.SqlTypeAssignement#getType <em>Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' containment reference.
   * @see #getType()
   * @generated
   */
  void setType(PojoType value);

} // SqlTypeAssignement
