/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea.lang


class ProcessorMetaFileType extends AbstractProcessorMetaFileType {
	public static final ProcessorMetaFileType INSTANCE = new ProcessorMetaFileType()
	
	new() {
		super(ProcessorMetaLanguage.INSTANCE)
	}
}
