/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.lang


class ProcessorModelFileType extends AbstractProcessorModelFileType {
	public static final ProcessorModelFileType INSTANCE = new ProcessorModelFileType()
	
	new() {
		super(ProcessorModelLanguage.INSTANCE)
	}
}
