/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.completion;

import org.sqlproc.model.idea.completion.AbstractProcessorModelCompletionContributor;
import org.sqlproc.model.idea.lang.ProcessorModelLanguage;

@SuppressWarnings("all")
public class ProcessorModelCompletionContributor extends AbstractProcessorModelCompletionContributor {
  public ProcessorModelCompletionContributor() {
    this(ProcessorModelLanguage.INSTANCE);
  }
  
  public ProcessorModelCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
