/**
 * generated by Xtext 2.12.0
 */
package org.sqlproc.model.ide;

import org.sqlproc.model.ide.AbstractProcessorModelIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class ProcessorModelIdeModule extends AbstractProcessorModelIdeModule {
}
