/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.tests;

import com.google.inject.Inject;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.junit4.InjectWith;
import org.eclipse.xtext.junit4.XtextRunner;
import org.eclipse.xtext.junit4.util.ParseHelper;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.sqlproc.meta.processorMeta.Artifacts;
import org.sqlproc.meta.tests.ProcessorMetaInjectorProvider;

@RunWith(XtextRunner.class)
@InjectWith(ProcessorMetaInjectorProvider.class)
@SuppressWarnings("all")
public class ProcessorMetaParsingTest {
  @Inject
  private ParseHelper<Artifacts> parseHelper;
  
  @Test
  public void loadModel() {
    try {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("Hello Xtext!");
      _builder.newLine();
      final Artifacts result = this.parseHelper.parse(_builder);
      Assert.assertNotNull(result);
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }
}
