/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea;

@SuppressWarnings("all")
public class ProcessorMetaIdeaSetup /* implements ISetup  */{
  @Override
  public Object createInjectorAndDoEMFRegistration() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method or field EcoreGlobalRegistries is undefined"
      + "\nThe method createInjector() from the type ProcessorMetaStandaloneSetupIdea refers to the missing type Object"
      + "\nensureInitialized cannot be resolved");
  }
}
