/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea;

import org.sqlproc.meta.idea.AbstractProcessorMetaIdeaModule;

/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
@SuppressWarnings("all")
public class ProcessorMetaIdeaModule extends AbstractProcessorMetaIdeaModule {
}
