/**
 * generated by Xtext 2.10.0
 */
package org.sqlproc.meta.processorMeta;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sqlproc.meta.processorMeta.Mapping#getMappingItems <em>Mapping Items</em>}</li>
 * </ul>
 *
 * @see org.sqlproc.meta.processorMeta.ProcessorMetaPackage#getMapping()
 * @model
 * @generated
 */
public interface Mapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Mapping Items</b></em>' containment reference list.
   * The list contents are of type {@link org.sqlproc.meta.processorMeta.MappingItem}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Mapping Items</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mapping Items</em>' containment reference list.
   * @see org.sqlproc.meta.processorMeta.ProcessorMetaPackage#getMapping_MappingItems()
   * @model containment="true"
   * @generated
   */
  EList<MappingItem> getMappingItems();

} // Mapping
