/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea.completion;

import org.sqlproc.meta.idea.completion.AbstractProcessorMetaCompletionContributor;

@SuppressWarnings("all")
public class ProcessorMetaCompletionContributor extends AbstractProcessorMetaCompletionContributor {
  public ProcessorMetaCompletionContributor() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe constructor ProcessorMetaCompletionContributor(AbstractXtextLanguage) refers to the missing type AbstractXtextLanguage");
  }
  
  public ProcessorMetaCompletionContributor(final /* AbstractXtextLanguage */Object lang) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AbstractXtextLanguage) is undefined");
  }
}
