/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ProcessorModelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/sqlproc/model/idea/parser/antlr/internal/PsiInternalProcessorModel.tokens");
	}
}
