/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea;

@SuppressWarnings("all")
public class ProcessorModelStandaloneSetupIdea /* implements ProcessorModelStandaloneSetupGenerated  */{
  @Override
  public Object createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nProcessorModelRuntimeModule cannot be resolved."
      + "\nThe method or field Modules2 is undefined"
      + "\nThe method or field Guice is undefined"
      + "\nmixin cannot be resolved"
      + "\ncreateInjector cannot be resolved");
  }
}
