/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.ui.labeling;

import org.eclipse.xtext.naming.QualifiedName;
import org.eclipse.xtext.resource.IEObjectDescription;
import org.eclipse.xtext.ui.label.DefaultDescriptionLabelProvider;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class ProcessorMetaDescriptionLabelProvider extends DefaultDescriptionLabelProvider {
  @Override
  public Object text(final IEObjectDescription ele) {
    QualifiedName _name = ele.getName();
    return ("" + _name);
  }
}
