/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.facet;

/* @State(, ) */@SuppressWarnings("all")
public class ProcessorModelFacetConfiguration /* implements XbaseFacetConfiguration, PersistentStateComponent<XbaseGeneratorConfigurationState>  */{
}
