/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea


/**
 * Use this class to register components to be used within IntelliJ IDEA.
 */
class ProcessorMetaIdeaModule extends AbstractProcessorMetaIdeaModule {
}
