/*
 * generated by Xtext 2.10.0
 */
package org.sqlproc.meta.idea.lang.parser;

import com.google.inject.Inject;
import com.intellij.lang.PsiBuilder;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import org.antlr.runtime.TokenStream;
import org.eclipse.xtext.idea.parser.AbstractPsiAntlrParser;
import org.eclipse.xtext.idea.parser.AbstractXtextPsiParser;
import org.sqlproc.meta.idea.lang.ProcessorMetaElementTypeProvider;
import org.sqlproc.meta.idea.parser.antlr.internal.PsiInternalProcessorMetaParser;
import org.sqlproc.meta.services.ProcessorMetaGrammarAccess;

public class ProcessorMetaPsiParser extends AbstractXtextPsiParser {

	private static final Set<String> INITIAL_HIDDEN_TOKENS = new HashSet<String>(Arrays.asList("RULE_ML_COMMENT", "RULE_SL_COMMENT"));

	@Inject 
	private ProcessorMetaGrammarAccess grammarAccess;

	@Inject 
	private ProcessorMetaElementTypeProvider elementTypeProvider;

	@Override
	protected AbstractPsiAntlrParser createParser(PsiBuilder builder, TokenStream tokenStream) {
		return new PsiInternalProcessorMetaParser(builder, tokenStream, elementTypeProvider, grammarAccess);
	}

	@Override
	protected Set<String> getInitialHiddenTokens() {
		return INITIAL_HIDDEN_TOKENS;
	}
}
