/*
 * generated by Xtext 2.10.0
 */
package org.sqlproc.meta.idea.lang;

import org.eclipse.xtext.idea.lang.AbstractXtextLanguage;

public final class ProcessorMetaLanguage extends AbstractXtextLanguage {

	public static final ProcessorMetaLanguage INSTANCE = new ProcessorMetaLanguage();

	private ProcessorMetaLanguage() {
		super("org.sqlproc.meta.ProcessorMeta");
	}

}
