/*
 * generated by Xtext 2.10.0
 */
package org.sqlproc.meta.idea;

import com.intellij.openapi.extensions.ExtensionFactory;
import org.sqlproc.meta.idea.lang.ProcessorMetaLanguage;

public class ProcessorMetaExtensionFactory implements ExtensionFactory {
	@Override
	public Object createInstance(String factoryArgument, String implementationClass) {
		Class<?> clazz;
		try {
			clazz = Class.forName(implementationClass);
		} catch (ClassNotFoundException e) {
			throw new IllegalArgumentException("Couldn't load "+implementationClass, e);
		}
		return ProcessorMetaLanguage.INSTANCE.<Object> getInstance(clazz);
	}
}
