/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.sqlproc.meta.parser.antlr.internal.InternalProcessorMetaParser;
import org.sqlproc.meta.services.ProcessorMetaGrammarAccess;

public class ProcessorMetaParser extends AbstractAntlrParser {

	@Inject
	private ProcessorMetaGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalProcessorMetaParser createParser(XtextTokenStream stream) {
		return new InternalProcessorMetaParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Artifacts";
	}

	public ProcessorMetaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ProcessorMetaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
