/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.idea.lang.psi.impl;

import com.intellij.openapi.fileTypes.FileType;
import com.intellij.psi.FileViewProvider;
import org.eclipse.xtext.psi.impl.BaseXtextFile;
import org.sqlproc.model.idea.lang.ProcessorModelFileType;
import org.sqlproc.model.idea.lang.ProcessorModelLanguage;

public final class ProcessorModelFileImpl extends BaseXtextFile {

	public ProcessorModelFileImpl(FileViewProvider viewProvider) {
		super(viewProvider, ProcessorModelLanguage.INSTANCE);
	}

	@Override
	public FileType getFileType() {
		return ProcessorModelFileType.INSTANCE;
	}
}
