/*
 * generated by Xtext 2.10.0
 */
package org.sqlproc.meta.idea.lang.psi;

import com.intellij.psi.util.PsiModificationTracker;
import org.eclipse.xtext.psi.BaseXtextCodeBlockModificationListener;
import org.sqlproc.meta.idea.lang.ProcessorMetaLanguage;

public class ProcessorMetaCodeBlockModificationListener extends BaseXtextCodeBlockModificationListener {

	public ProcessorMetaCodeBlockModificationListener(PsiModificationTracker psiModificationTracker) {
		super(ProcessorMetaLanguage.INSTANCE, psiModificationTracker);
	}

}
