/**
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model.ui.quickfix;

import org.eclipse.xtext.xbase.annotations.ui.quickfix.XbaseWithAnnotationsQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#quick-fixes
 */
@SuppressWarnings("all")
public class ProcessorModelQuickfixProvider extends XbaseWithAnnotationsQuickfixProvider {
}
