/*
 * generated by Xtext 2.11.0.RC2
 */
 package org.sqlproc.model.ide


/**
 * Use this class to register ide components.
 */
class ProcessorModelIdeModule extends AbstractProcessorModelIdeModule {
}
