/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ProcessorModelRuntimeModule extends AbstractProcessorModelRuntimeModule {
}
