/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ProcessorModelStandaloneSetup extends ProcessorModelStandaloneSetupGenerated {

	def static void doSetup() {
		new ProcessorModelStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
