/*
 * generated by Xtext 2.10.0-SNAPSHOT
 */
package org.sqlproc.meta.idea

import org.eclipse.xtext.ISetup
import org.eclipse.xtext.idea.extensions.EcoreGlobalRegistries

class ProcessorMetaIdeaSetup implements ISetup {

	override createInjectorAndDoEMFRegistration() {
		EcoreGlobalRegistries.ensureInitialized
		new ProcessorMetaStandaloneSetupIdea().createInjector
	}

}
